<?php

namespace AppBundle\Repository;

/**
 * EspeceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspeceRepository extends \Doctrine\ORM\EntityRepository
{
}
