<?php

namespace AppBundle\Repository;

/**
 * TraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitementRepository extends \Doctrine\ORM\EntityRepository
{
}
