<?php

namespace AppBundle\Repository;

/**
 * VetoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VetoRepository extends \Doctrine\ORM\EntityRepository
{
}
